// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwbtwzzrgeeskcuffxwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YnR3enpyZ2Vlc2tjdWZmeHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NDQ3MjIsImV4cCI6MjA1MTQyMDcyMn0.7xqMdvZTBG0LWBTrDnW58btL1uMVUDKur30QNV0p3AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);